added italian translation
xou816/spot pull request #446
Opened 2022-01-18 21:10 UTC by fbabetto

Hi,
first of all thank you for spot, I really like it!
I just added the Italian translation, I'm 99,99% satisfied by this translation, maybe in the future I'll post an update because I'm not completely satisfied by some string.

2022-01-18 21:21 UTC, fbabetto commented
Sorry, I didn't notice there was a template to follow, I'll update this PR soon :)

2022-01-19 19:58 UTC, fbabetto commented
Fixed, read to be pulled.

2022-01-21 23:47 UTC, xou816 commented
Hi! Thank you for taking the time to contribute these translations! :) 

Don't worry, we don't have a template, as files get regenerated fairly often anyway. By the way, you can directly contribute on [POEditor](https://poeditor.com/join/project?hash=xfVrpQfRBM) if you want to!

As for the PR, you'll just need to add the it code to LINGUAS for this code to work, otherwise the file seems to be properly formatted! :)

2022-01-21 23:48 UTC, xou816 requested changes
(missing it code in LINGUAS)

2022-01-24 17:59 UTC, fbabetto commented
Done!

2022-01-29 16:03 UTC, xou816 commented
looking good :) merging, thank you very much!

2022-01-29 16:03 UTC, merged